#pragma once

#include <string>
#include <unordered_map>

enum class key_event
{
	pressed		= 0,
	released	= 1,
	repeat		= 2,
};

static std::string key_event_to_string(key_event t_key_event)
{
	const static std::unordered_map<key_event, std::string> key_event_str_table =
	{
		{ key_event::pressed,	"pressed" },
		{ key_event::released,	"released" },
		{ key_event::repeat,	"repeat" },

	};
	return key_event_str_table.at(t_key_event);
}

enum class key
{
	unknown				= 0,
	space				= 1,
	apostrophe			= 2,
	comma				= 3,
	minus				= 4,
	period				= 5,
	slash				= 6,
	zero				= 7,
	one					= 8,
	two					= 9,
	three				= 10,
	four				= 11,
	five				= 12,
	six					= 13,
	seven				= 14,
	eight				= 15,
	nine				= 16,
	semicolon			= 17,
	equal				= 18,
	a					= 19,
	b					= 20,
	c					= 21,
	d					= 22,
	e					= 23,
	f					= 24,
	g					= 25,
	h					= 26,
	i					= 27,
	j					= 28,
	k					= 29,
	l					= 30,
	m					= 31,
	n					= 32,
	o					= 33,
	p					= 34,
	q					= 35,
	r					= 36,
	s					= 37,
	t					= 38,
	u					= 39,
	v					= 40,
	w					= 41,
	x					= 42,
	y					= 43,
	z					= 44,
	left_bracket		= 45,
	backslash			= 46,
	right_bracket		= 47,
	grave_accent		= 48,
	world_1				= 49,
	world_2				= 50,
	escape				= 51,
	enter				= 52,
	tab					= 53,
	backspace			= 54,
	insert				= 55,
	del					= 56,
	right				= 57,
	left				= 58,
	down				= 59,
	up					= 60,
	page_up				= 61,
	page_down			= 62,
	home				= 63,
	end					= 64,
	caps_lock			= 65,
	scroll_lock			= 66,
	num_lock			= 67,
	print_screen		= 68,
	pause				= 69,
	f1					= 70,
	f2					= 71,
	f3					= 72,
	f4					= 73,
	f5					= 74,
	f6					= 75,
	f7					= 76,
	f8					= 77,
	f9					= 78,
	f10					= 79,
	f11					= 80,
	f12					= 81,
	f13					= 82,
	f14					= 83,
	f15					= 84,
	f16					= 85,
	f17					= 86,
	f18					= 87,
	f19					= 88,
	f20					= 89,
	f21					= 90,
	f22					= 91,
	f23					= 92,
	f24					= 93,
	f25					= 94,
	kp_0				= 95,
	kp_1				= 96,
	kp_2				= 97,
	kp_3				= 98,
	kp_4				= 99,
	kp_5				= 100,
	kp_6				= 101,
	kp_7				= 102,
	kp_8				= 103,
	kp_9				= 104,
	kp_decimal			= 105,
	kp_divide			= 106,
	kp_multiply			= 107,
	kp_subtract			= 108,
	kp_add				= 109,
	kp_enter			= 110,
	kp_equal			= 111,
	left_shift			= 112,
	left_control		= 113,
	left_alt			= 114,
	left_super			= 115,
	right_shift			= 116,
	right_control		= 117,
	right_alt			= 118,
	right_super			= 119,
	menu				= 120,

	mouse_button_1		= 121,
	mouse_button_2		= 122,
	mouse_button_middle	= 123,
	mouse_button_4		= 124,
	mouse_button_5		= 125,
	mouse_button_6		= 126,
	mouse_button_7		= 127,
	mouse_button_8		= 128,

	max					= 129,
};

static std::string key_to_string(key t_key)
{
	const static std::unordered_map<key, std::string> key_str_table = 
	{
		{ key::unknown,				"unknown" },
		{ key::space,				"space" },
		{ key::apostrophe,			"apostrophe" },
		{ key::comma,				"comma" },
		{ key::minus,				"minus" },
		{ key::period,				"period" },
		{ key::slash,				"slash" },
		{ key::zero,				"zero" },
		{ key::one,					"1" },
		{ key::two,					"2" },
		{ key::three,				"3" },
		{ key::four,				"4" },
		{ key::five,				"5" },
		{ key::six,					"6" },
		{ key::seven,				"7" },
		{ key::eight,				"8" },
		{ key::nine,				"9" },
		{ key::semicolon,			"semicolon" },
		{ key::equal,				"equal" },
		{ key::a,					"a" },
		{ key::b,					"b" },
		{ key::c,					"c" },
		{ key::d,					"d" },
		{ key::e,					"e" },
		{ key::f,					"f" },
		{ key::g,					"g" },
		{ key::h,					"h" },
		{ key::i,					"i" },
		{ key::j,					"j" },
		{ key::k,					"k" },
		{ key::l,					"l" },
		{ key::m,					"m" },
		{ key::n,					"n" },
		{ key::o,					"o" },
		{ key::p,					"p" },
		{ key::q,					"q" },
		{ key::r,					"r" },
		{ key::s,					"s" },
		{ key::t,					"t" },
		{ key::u,					"u" },
		{ key::v,					"v" },
		{ key::w,					"w" },
		{ key::x,					"x" },
		{ key::y,					"y" },
		{ key::z,					"z" },
		{ key::left_bracket,		"left_bracket" },
		{ key::backslash,			"backslash" },
		{ key::right_bracket,		"right_bracket" },
		{ key::grave_accent,		"grave_accent" },
		{ key::world_1,				"world_1" },
		{ key::world_2,				"world_2" },
		{ key::escape,				"escape" },
		{ key::enter,				"enter" },
		{ key::tab,					"tab" },
		{ key::backspace,			"backspace" },
		{ key::insert,				"insert" },
		{ key::del,					"del" },
		{ key::right,				"right" },
		{ key::left,				"left" },
		{ key::down,				"down" },
		{ key::up,					"up" },
		{ key::page_up,				"page_up" },
		{ key::page_down,			"page_down" },
		{ key::home,				"home" },
		{ key::end,					"end" },
		{ key::caps_lock,			"caps_lock" },
		{ key::scroll_lock,			"scroll_lock" },
		{ key::num_lock,			"num_lock" },
		{ key::print_screen,		"print_screen" },
		{ key::pause,				"pause" },
		{ key::f1,					"f1" },
		{ key::f2,					"f2" },
		{ key::f3,					"f3" },
		{ key::f4,					"f4" },
		{ key::f5,					"f5" },
		{ key::f6,					"f6" },
		{ key::f7,					"f7" },
		{ key::f8,					"f8" },
		{ key::f9,					"f9" },
		{ key::f10,					"f10" },
		{ key::f11,					"f11" },
		{ key::f12,					"f12" },
		{ key::f13,					"f13" },
		{ key::f14,					"f14" },
		{ key::f15,					"f15" },
		{ key::f16,					"f16" },
		{ key::f17,					"f17" },
		{ key::f18,					"f18" },
		{ key::f19,					"f19" },
		{ key::f20,					"f20" },
		{ key::f21,					"f21" },
		{ key::f22,					"f22" },
		{ key::f23,					"f23" },
		{ key::f24,					"f24" },
		{ key::f25,					"f25" },
		{ key::kp_0,				"kp_0" },
		{ key::kp_1,				"kp_1" },
		{ key::kp_2,				"kp_2" },
		{ key::kp_3,				"kp_3" },
		{ key::kp_4,				"kp_4" },
		{ key::kp_5,				"kp_5" },
		{ key::kp_6,				"kp_6" },
		{ key::kp_7,				"kp_7" },
		{ key::kp_8,				"kp_8" },
		{ key::kp_9,				"kp_9" },
		{ key::kp_decimal,			"kp_decimal" },
		{ key::kp_divide,			"kp_divide" },
		{ key::kp_multiply,			"kp_multiply" },
		{ key::kp_subtract,			"kp_subtract" },
		{ key::kp_add,				"kp_add" },
		{ key::kp_enter,			"kp_enter" },
		{ key::kp_equal,			"kp_equal" },
		{ key::left_shift,			"left_shift" },
		{ key::left_control,		"left_control" },
		{ key::left_alt,			"left_alt" },
		{ key::left_super,			"left_super" },
		{ key::right_shift,			"right_shift" },
		{ key::right_control,		"right_control" },
		{ key::right_alt,			"right_alt" },
		{ key::right_super,			"right_super" },
		{ key::menu,				"menu" },

		{ key::mouse_button_1,		"mouse_button_1" },
		{ key::mouse_button_2,		"mouse_button_2" },
		{ key::mouse_button_middle,	"mouse_button_middle" },
		{ key::mouse_button_4,		"mouse_button_4" },
		{ key::mouse_button_5,		"mouse_button_5" },
		{ key::mouse_button_6,		"mouse_button_6" },
		{ key::mouse_button_7,		"mouse_button_7" },
		{ key::mouse_button_8,		"mouse_button_8" },
	};

	return key_str_table.at(t_key);
}
